{% set name = "cvloop" %}
{% set version = "0.3.5" %}
{% set sha256 = "67b853b514f02d02f63ac90455595f0a8a5817b7c25d629a05bc82beb369dca6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py<36]

requirements:
  build:
    - python
  run:
    - python
    - opencv
    - numpy
    - matplotlib-base
    - jupyter

test:
  imports:
    - cvloop

about:
  home: http://github.com/shoeffner/cvloop
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Online video processing in jupyter notebooks'
  description: |
      cvloop allows online video transformation and evaluation with OpenCV.
      It is designed for jupyter notebooks, but works without as well.
  doc_url: https://github.com/shoeffner/cvloop/blob/master/examples/cvloop_examples.ipynb
  dev_url: https://github.com/shoeffner/cvloop

extra:
  recipe-maintainers:
    - shoeffner
