travis:
  secure:
    BINSTAR_TOKEN: yfuuO+m8FyDmwvPZk0nW1f5LyMqy9XSYIzu9IMLSMw/nbGVzqOf3FGCyRJpp0XYWbtkdqoX56wOW2dYMVnhIlJ+X1jWW8jERmqTX4xtwGf3sHL3LqIK/fEpLjAtGYsoB4Siyob8hffnO+5D+jtl9CcVhYK2nva4P1OjkR4m1C9Jw0GObFi/C2W0yb5Womo9thS2ZvlrN9OS1fZFk74Y4mWDwiiAMvefOyAlGxKLQYuYE+wtH5Y+b9U1IR3i/G6ywGREcRTB4GfwvX2Q6ZBeSejp/dsUpNN2qJqwvPlCmBZvuqYg2pXfzAzXNls4XwA+llr8/oDUetefl9SG9EnwLEdV/dL0mnd9dnCG4Imq/qnKjv3TfkwiNK54MLhy8YkyGyIDiSIbUJEkdoLVyCU7ibhIOIF/Va9ccLYsZZ5/TSWbA3Z9wDbxW5THP1cAbQIziv3aAVO4ivbE0m8g1IKu7iiL3kCCznUJIJQrXSiA2/wmA5wpRDUiI8/SIt+lgys9zGvbCpu1Ws46IbmdHvpa0HESTsSwI6if+yXWgy2DrEhu5cQ3yPEKKwAiU2k71p11ktIt3J3NnAImtgfX8t6NpanmDQhMuXLpha4ImuZb04PcLaV01QAIhtS6few1gFIpFMWqPBHuNhjDY7O2yyWHJ9/NJYQ4B/D2hojy1om3mgKM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
